development:
  adapter: postgresql
  host: localhost
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  database: hnhiring_dev
  username: postgres
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hnhiring_dev
  encoding: unicode
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  database: hnhiring_test
  username: postgres
  encoding: unicode
  pool: 5
  timeout: 5000
